### ISSUE TITLE
No rule to make target `libsecp256k1.la'.  Stop.

### ISSUE THREAD

**Issue by meeDamian** [kallewoof/btcdeb#2]
I've cloned and compiled the project before & it worked.

After a recent pull and running:

```
./autogen.sh
./configure
make
```

With the last command, I'm getting:

```
  CXX      btcdeb-btcdeb.o
  CXX      libbitcoin_a-base58.o
  CXX      libbitcoin_a-bech32.o
  CXX      crypto/libbitcoin_a-hmac_sha512.o
  CXX      crypto/libbitcoin_a-ripemd160.o
  CXX      crypto/libbitcoin_a-sha1.o
  CXX      crypto/libbitcoin_a-sha256.o
  CXX      crypto/libbitcoin_a-sha512.o
  CXX      libbitcoin_a-hash.o
  CXX      libbitcoin_a-interpreter.o
  CXX      primitives/libbitcoin_a-transaction.o
  CXX      libbitcoin_a-pubkey.o
  CXX      libbitcoin_a-script.o
  CXX      libbitcoin_a-script_error.o
  CXX      support/libbitcoin_a-cleanse.o
  CXX      libbitcoin_a-uint256.o
  CXX      libbitcoin_a-utilstrencodings.o
make[2]: *** No rule to make target `libsecp256k1.la'.  Stop.
make[1]: *** [secp256k1/libsecp256k1.la] Error 2
make: *** [all-recursive] Error 1
```

I lack experience with C++. Any way to fix it?

**Comment by kallewoof** [comment]
Thanks for the report! Apparently the libsecp256k1 module was not autogenerated correctly, due to me fatfingering the path.

I've pushed a fix. When you pull, you may be given an error about overwriting files in `build-aux`. Delete the files it complains about and try again until it succeeds. These files should not have been in the repo.

**Comment by meeDamian** [comment]
pulled, and everything works great now :). Thanks!
